services:
  postgres:
    image: postgres:16
    container_name: sobrevidas-postgres
    environment:
      POSTGRES_DB: pacientesdb
      POSTGRES_USER: sobrevidas
      POSTGRES_PASSWORD: sobrevidas123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: sobrevidas-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
    ports:
      - "8180:8080"
    command: start-dev

volumes:
  postgres_data: